### ISSUE TITLE
Callout pack tags

### ISSUE THREAD

**Issue by Michael21107** [YobB1n/YobbinCallouts#12]
add some tags to the internal name of the callouts to easily distinguish them from the ones from other packs in places such as the [Callout Interface](https://www.lcpdfr.com/downloads/gta5mods/scripts/37828-callout-interface/) or LSPDFR native callout lists (the image shows how Yobin and [Super Callouts](https://github.com/SuperPyroManiac/SuperPlugins/tree/master/SuperCallouts) (SC) look next to each other on the native LSPDFR callout list)
![image](https://github.com/YobB1n/YobbinCallouts/assets/121039033/557ffb71-af7f-4fe7-9611-73c1fe0c86b2)

**Comment by jonjongames1997** [comment]
@Michael21107 Why does that even matter? It's his callout pack, he can do whatever he wants to do with it.
